CC=gcc
CFLAGS=-Wall -O2
LDFLAGS=-lm

OBJECTS=main.o

simplesh: $(OBJECTS)
	$(CC) $(CFLAGS) $(OBJECTS) $(LDFLAGS) -o simplesh

main.o: main.c
	$(CC) $(CFLAGS) -c main.c

clean:
	rm -f $(OBJECTS) simplesh

check: simplesh test.txt
	./simplesh < test.txt

dist:

all: simplesh